### ISSUE TITLE
Multiple compilation errors

### ISSUE THREAD

**Issue by d4rkmen** [mongoose-os-apps/fingerprint-demo#1]
It seems this source and underlying fingerprint lib has many compilation errors
Unable to build 👎

**Comment by pimvanpelt** [comment]
Filing this type of issue is very unhelpful. Perhaps you're new to F/OSS or Github, so let me give you an [example](https://www.ccsguidelineprograms.ca/2018/10/09/5-etiquette-tips-to-follow-when-reporting-bugs-to-your-developer-company/) on how to interact with developers like me.

Why don't you attempt to understand the many compilation errors you have found, fix them (perhaps on your side, perhaps in the underlying fingerprint library, and perhaps in this demo), and send me a PR?

```
git clone git@github.com:mongoose-os-apps/fingerprint-demo.git
cd fingerprint-demo
mos build --verbose --local

<...>
Success, built fingerprint-demo/esp32 version 1.0 (20201014-093408/2.17.0-gd5afc75-master).
Firmware saved to /home/pim/src/fingerprint-demo/build/fw.zip
```

**Comment by d4rkmen** [comment]
Cool. Now try the same with remote build ;)

**Comment by pimvanpelt** [comment]
I do not operate or support remote builds, and you're still having a bit of difficulties actually filing a helpful issue on github, so I'm not going to reply further on this issue.

git clone git@github.com:mongoose-os-apps/fingerprint-demo.git
cd ~/src/fingerprint-demo
mos build

Connecting to https://mongoose.cloud, user test
Uploading sources (2716 bytes)
Firmware saved to /home/pim/src/fingerprint-demo/build/fw.zip

**Comment by d4rkmen** [comment]
Yes, sorry. I missed its for ESP32 only. I was tried to compile for 8266.
